name: amr
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.8.0=h8bc59a9_15
  - aws-c-cal=0.8.1=hc8a0bd2_3
  - aws-c-common=0.10.6=h5505292_0
  - aws-c-compression=0.3.0=hc8a0bd2_5
  - aws-c-event-stream=0.5.0=h54f970a_11
  - aws-c-http=0.9.2=h96aa502_4
  - aws-c-io=0.15.3=haba67d1_6
  - aws-c-mqtt=0.11.0=h24f418c_12
  - aws-c-s3=0.7.7=h1be5864_0
  - aws-c-sdkutils=0.2.1=hc8a0bd2_4
  - aws-checksums=0.2.2=hc8a0bd2_4
  - aws-crt-cpp=0.29.7=h19a973c_7
  - aws-sdk-cpp=1.11.458=he0ff2e4_4
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - blas=1.0=openblas
  - blast=2.16.0=hb260f6e_5
  - bottleneck=1.4.2=py310h03d0aa3_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - curl=8.16.0=h6430ca7_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrez-direct=22.4=hd5f1084_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py310h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h8086d47_1
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - hmmer=3.4=haef7865_3
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jansson=2.14=h80987f9_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.8=py310h313beb8_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libarrow=18.1.0=h86d57b8_4_cpu
  - libarrow-acero=18.1.0=h1dc2043_4_cpu
  - libarrow-dataset=18.1.0=h1dc2043_4_cpu
  - libarrow-substrait=18.1.0=hf3d3107_4_cpu
  - libavif=1.1.1=h80987f9_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=5_h880f123_netlib
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libgoogle-cloud=2.31.0=h8d8be31_0
  - libgoogle-cloud-storage=2.31.0=h7081f7f_0
  - libgrpc=1.67.1=hc70892a_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - liblapack=3.9.0=5_h880f123_netlib
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libparquet=18.1.0=hf4cc9e7_4_cpu
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.28.2=h8f0b736_0
  - libre2-11=2024.07.02=h07bc746_2
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h9a5124b_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.0=h91aec0a_0
  - libtorch=2.5.1=cpu_generic_hf3ddf7c_7
  - libunistring=1.3=h1799b2a_0
  - libutf8proc=2.9.0=h5505292_1
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib=3.10.6=py310hca03da5_1
  - matplotlib-base=3.10.6=py310h37b8ce2_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncbi-amrfinderplus=4.0.23=h3496714_0
  - ncbi-vdb=3.2.1=h4675bf2_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.14.1=py310h5fbe615_0
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openssl=3.6.0=h5503f6c_0
  - orc=2.0.3=h121fd32_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h3f644e9_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1dacb4a_0
  - perl=5.32.1=0_h1a28f6b_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.38=pl5340hca03da5_0
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.214=pl5321h2ddc596_0
  - perl-compress-raw-zlib=2.214=pl5321ha1c2b25_0
  - perl-encode=3.21=pl5321h5505292_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.3506=pl5340hca03da5_0
  - perl-io-compress=2.213=pl5321haef7865_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h4675bf2_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321hbdacb55_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hc71e825_2
  - perl-scalar-list-utils=1.70=pl5321h44e845a_0
  - perl-storable=3.15=pl5321hc71e825_2
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py310he2d6fe4_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prodigal=2.6.3=hba9b596_11
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310hf151d32_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=18.1.0=py310hb6292c7_0
  - pyarrow-core=18.1.0=py310hc17921c_0_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py310hca03da5_0
  - python=3.10.15=hdce6c4c_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=cpu_generic_py310_hbae1486_7
  - pytz=2025.2=py310hca03da5_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - re2=2024.07.02=h6589ca4_2
  - readline=8.3=h0b18652_0
  - rpsbproc=0.5.0=hf8bb5b5_3
  - scikit-learn=1.7.2=py310hc6ded6b_0
  - scipy=1.15.3=py310h132fc3c_1
  - seaborn=0.13.2=py310hca03da5_3
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py310hfe3a0ae_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wget=1.25.0=hbc1a67d_2
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Users/jackpapciak/miniconda3/envs/amr
